sys:
  icore: dummy://preview-only
  input:
    gray_dir: ./io/gray
    rgb_dir: ./io/rgb
    fps: 10
    loop: false
  display:
    type: dump
    width: 1920
    height: 1080
    fps: 60
  output:
    mode: dump
    dump_dir: ./io/output
